name: docker-compose-actions-workflow
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
      - 'c*'
  workflow_dispatch:
defaults:
  run:
    shell: bash
    
jobs:
  build:
    runs-on: macos-11
    env:
      targetIPA: ios-ipa-helloworld-cmake-${{ github.ref_name }}.ipa
    steps:
      - uses: actions/checkout@v3
          
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '13.0.0'
          
      - name: Show Xcode version
        run: xcodebuild -version
      
      - name: build
        run: |
          cmake -G"Xcode" -DCMAKE_BUILD_TYPE=Debug -B./cmake-build && cd cmake-build && cmake --build . && \
          xcodebuild -project "ios-ipa-helloworld-cmake.xcodeproj"  archive -destination 'generic/platform=iOS' -scheme "ios-ipa-helloworld-cmake" -archivePath "./ios-ipa-helloworld-cmake.xcarchive" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO CODE_SIGN_IDENTITY= CODE_SIGN_ENTITLEMENTS= GCC_OPTIMIZATION_LEVEL=s SWIFT_OPTIMIZATION_LEVEL=-O && \
          mkdir -p ipa/Payload && \
          cp -r ./Release-iphoneos/ios-ipa-helloworld-cmake.app  ./ipa/Payload && \
          cd ipa && \
          zip -r ../${{ env.targetIPA }} *
          
#      - uses: fastai/workflows/ssh@master
#        with:
#          ssh_key: ${{ secrets.SSH_KEY }}
#          key_file: id_ecdsa
#        
#  # - uses: actions/checkout@v2
#  # - run: source script-mac.sh
#      - name: Setup tmate session
#        uses: mxschmitt/action-tmate@v2

      - name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          artifacts: "cmake-build/${{ env.targetIPA }}"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
